stages:
  - lint
  - unit_tests

before_script:
  - bundle exec pod install

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - fastlane test
  tags:
    - ios
  
lint:
  dependencies: []
  stage: lint
  script:
    - fastlane lint
  tags:
    - ios
