stages:
  - lint
  - unit_tests

before_script:
  - ruby -v
  - which ruby
  - sudo gem install bundler --no-ri --no-rdoc
  - bundle install
  - bundle exec pod install

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - fastlane test
  tags:
    - ios
  
lint:
  dependencies: []
  stage: lint
  script:
    - fastlane lint
  tags:
    - ios
