stages:
  - unit_tests
  - lint
  
variables:
  CI_DEBUG_TRACE: "true"
  
before_script:
  - bundle install
  - bundle exec pod install

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - fastlane test
  tags:
    - ios
  
lint:
  dependencies: []
  stage: lint
  script:
    - fastlane lint
  tags:
    - ios
