stages:
  - build
  - lint
  - unit_tests

before_script:
  - bundle install --path vendor/bundle
  - bundle exec pod install

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - fastlane test
  tags:
    - ios
  
lint:
  dependencies: []
  stage: lint
  script:
    - fastlane lint
  tags:
    - ios

build:
  dependencies: []
  stage: build
  script:
    - fatslane build
  tags:
    - ios
