stages:
  - lint
  - unit_tests

before_script:
  - gem install CFPropertyList -v '3.0.2' --source 'https://rubygems.org/'
  - bundle install
  - rm Gemfile.lock
  - bundle update --all
  - bundle exec pod install

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - fastlane test
  tags:
    - ios
  
lint:
  dependencies: []
  stage: lint
  script:
    - fastlane lint
  tags:
    - ios
