# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
  lane :lint do
     swiftlint(
     mode: :lint,
     executable: "Pods/SwiftLint/swiftlint",
     reporter: "html",
     output_file: "fastlane/swiftlint-results.html",
     config_file: '.swiftlint.yml',
     ignore_exit_status: true
     )
  end
  desc "build the project"
  lane :build do
     gym(
     workspace: "LOFOTunisia.xcworkspace",
     configuration: "Stubs",
     skip_package_ipa: true,
     include_bitcode: true,
     skip_archive: true,
     silent: true,
     clean: true
  )
  end
  desc "Test an measure code coverage"
  lane :test do
    run_tests(devices: ["iPhone 8"],
    slack_url: "https://hooks.slack.com/services/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",
    slack_channel: "#lofo-qa")
  end
end
